---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cmd-exec-logs-volume
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/ubuntu/cmd-exec-logs-volume"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cmd-exec-logs-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cmd-exec-keys-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/ubuntu/cmd-exec-keys-volume"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cmd-exec-keys-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmd-exec
  labels:
    com.dagknows.service: cmd-exec
spec:
  replicas: 1
  selector:
    matchLabels:
      com.dagknows.service: cmd-exec
  template:
    metadata:
      labels:
        com.dagknows.service: cmd-exec
    spec:
      containers:
        - name: cmd-exec
          image: gcr.io/{{SUPER_USER_ORG}}-dagknows-images/cmd_exec:latest ## - To be replaced by GCR image.
          imagePullPolicy: "Always"
          command: ["python", "src/cmd_exec.py"]
          volumeMounts:
            - mountPath: /usr/src/app/logs
              name: logs-vol
            - mountPath: /usr/src/app/keys
              name: keys-vol
#            - name: secrets-vol
#              mountPath: /usr/src/app/src/keys/public_key.pem
#              subPath: public_key.pem
      volumes:
        - name: logs-vol
          persistentVolumeClaim:
            claimName: cmd-exec-logs-pvc
        - name: keys-vol
          persistentVolumeClaim:
            claimName: cmd-exec-keys-pvc
#        - name: secrets-vol
#          secret:
#            secretName: frontend-keys
#            items:
#              - key: public_key.pem
#                path: public_key.pem
---
apiVersion: v1
kind: Service
metadata:
  name: cmd-exec
  labels:
    com.dagknows.service: cmd-exec
spec:
  clusterIP: None
  ports:
    - port: 5434
      name: serving
  selector:
    com.dagknows.service: cmd-exec
