---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: script-exec-volume0
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/ubuntu/script-exec-volume"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: script-exec-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: script-exec
  labels:
    com.dagknows.service: script-exec
spec:
  replicas: 1
  selector:
    matchLabels:
      com.dagknows.service: script-exec
  template:
    metadata:
      labels:
        com.dagknows.service: script-exec
    spec:
      containers:
        - name: script-exec
          image: gcr.io/{{SUPER_USER_ORG}}-dagknows-images/script_exec:latest ## - To be replaced by GCR image.
          imagePullPolicy: "Always"
          command: ["python", "src/script_exec.py"]
          env:
            - name: DAGKNOWS_URL
              valueFrom:
                secretKeyRef:
                  name: com.dagknows.secret.frontend
                  key: DAGKNOWS_URL
            - name: PYTHONPATH
              value: "/usr/src/app/src/userlibs"
            - name: PROXY_SESSION_ID
              valueFrom:
                secretKeyRef:
                  name: com.dagknows.secret.frontend
                  key: PROXY_SESSION_ID
          volumeMounts:
            - mountPath: /usr/src/app/logs
              name: logs-vol
      volumes:
        - name: logs-vol
          persistentVolumeClaim:
            claimName: script-exec-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: script-exec
  labels:
    com.dagknows.service: script-exec
spec:
  clusterIP: None
  ports:
    - port: 5434
      name: serving
  selector:
    com.dagknows.service: script-exec
