---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cmd-exec-logs-pvc
  finalizers:
  - kubernetes
spec:
  storageClassName: {{PROXY_NAMESPACE}}-efs-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      purpose: cmdexec-logs
      namespace: {{PROXY_NAMESPACE}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cmd-exec-keys-pvc
  finalizers:
  - kubernetes
spec:
  storageClassName: {{PROXY_NAMESPACE}}-efs-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  selector:
    matchLabels:
      purpose: cmdexec-keys
      namespace: {{PROXY_NAMESPACE}}
