---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{PROXY_NAMESPACE}}-outpost-logs-volume
  labels:
    purpose: outpost-logs
    namespace: {{PROXY_NAMESPACE}}
spec:
  storageClassName: {{PROXY_NAMESPACE}}-efs-storageclass
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{OUTPOST_LOGS_EFS_FILESYSTEM_ID}}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{PROXY_NAMESPACE}}-outpost-jobs-volume
  labels:
    purpose: outpost-jobs
    namespace: {{PROXY_NAMESPACE}}
spec:
  storageClassName: {{PROXY_NAMESPACE}}-efs-storageclass
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{OUTPOST_JOBS_EFS_FILESYSTEM_ID}}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{PROXY_NAMESPACE}}-outpost-sidecar-volume
  labels:
    purpose: outpost-sidecar
    namespace: {{PROXY_NAMESPACE}}
spec:
  storageClassName: {{PROXY_NAMESPACE}}-efs-storageclass
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{OUTPOST_SIDECAR_EFS_FILESYSTEM_ID}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: outpost-logs-pvc
spec:
  storageClassName: {{PROXY_NAMESPACE}}-efs-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      purpose: outpost-logs
      namespace: {{PROXY_NAMESPACE}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: outpost-sidecar-pvc
spec:
  storageClassName: {{PROXY_NAMESPACE}}-efs-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  selector:
    matchLabels:
      purpose: outpost-logs
      namespace: {{PROXY_NAMESPACE}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: outpost-jobs-pvc
spec:
  storageClassName: {{PROXY_NAMESPACE}}-efs-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      purpose: outpost-keys
      namespace: {{PROXY_NAMESPACE}}
