---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vault-data-pvc
  finalizers:
  - kubernetes
spec:
  storageClassName: {{PROXY_NAMESPACE}}-efs-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      purpose: vault-data
      namespace: {{PROXY_NAMESPACE}}
