---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{PROXY_NAMESPACE}}-vault-data-volume
  labels:
    purpose: vault-data
    namespace: {{PROXY_NAMESPACE}}
  finalizers:
  - kubernetes
spec:
  storageClassName: {{PROXY_NAMESPACE}}-efs-storageclass
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{VAULT_DATA_EFS_FILESYSTEM_ID}}
