---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cmd-exec-logs-pvc
spec:
  storageClassName: {{PROXY_NAMESPACE}}-efs-storageclass-cmd-exec-logs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cmd-exec-keys-pvc
spec:
  storageClassName: {{PROXY_NAMESPACE}}-efs-storageclass-cmd-exec-keys
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
