---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: outpost-logs-pvc
spec:
  storageClassName: {{PROXY_NAMESPACE}}-efs-storageclass-outpost-logs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      purpose: outpost-logs
      namespace: {{PROXY_NAMESPACE}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: outpost-sidecar-pvc
spec:
  storageClassName: {{PROXY_NAMESPACE}}-efs-storageclass-outpost-sidecar
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  selector:
    matchLabels:
      purpose: outpost-sidecar
      namespace: {{PROXY_NAMESPACE}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: outpost-jobs-pvc
spec:
  storageClassName: {{PROXY_NAMESPACE}}-efs-storageclass-outpost-jobs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      purpose: outpost-jobs
      namespace: {{PROXY_NAMESPACE}}
