---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: outpost-logs-pvc
spec:
  storageClassName: {{PROXY_NAMESPACE}}-efs-storageclass-outpost-logs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: outpost-sidecar-pvc
spec:
  storageClassName: {{PROXY_NAMESPACE}}-efs-storageclass-outpost-sidecar
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: outpost-jobs-pvc
spec:
  storageClassName: {{PROXY_NAMESPACE}}-efs-storageclass-outpost-jobs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
