---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{PROXY_NAMESPACE}}-cmd-exec-logs-volume
  labels:
    purpose: cmd-exec-logs
    namespace: {{PROXY_NAMESPACE}}
spec:
  storageClassName: cmd-exec-storageclass
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "{{MINIKUBE_MOUNT_ROOT}}/cmd-exec/logs"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{PROXY_NAMESPACE}}-cmd-exec-keys-volume
  labels:
    purpose: cmd-exec-keys
    namespace: {{PROXY_NAMESPACE}}
spec:
  storageClassName: cmd-exec-storageclass
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "{{MINIKUBE_MOUNT_ROOT}}/cmd-exec/keys"
