---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vault-data-pvc
spec:
  storageClassName: vault-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      purpose: vault-data
      namespace: {{PROXY_NAMESPACE}}
