---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmd-exec
  labels:
    com.dagknows.service: cmd-exec
spec:
  replicas: 1
  selector:
    matchLabels:
      com.dagknows.service: cmd-exec
  template:
    metadata:
      labels:
        com.dagknows.service: cmd-exec
    spec:
      containers:
        - name: cmd-exec
          image: public.ecr.aws/n5k3t9x2/cmd_exec:latest ## - To be replaced by GCR image.
          imagePullPolicy: "Always"
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 500Mi
          command: ["python", "src/cmd_exec.py"]
          volumeMounts:
            - mountPath: /usr/src/app/logs
              name: logs-vol
            - mountPath: /usr/src/app/src/keys
              name: keys-vol
      volumes:
        - name: logs-vol
          persistentVolumeClaim:
            claimName: cmd-exec-logs-pvc
        - name: keys-vol
          persistentVolumeClaim:
            claimName: cmd-exec-keys-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cmd-exec
  labels:
    com.dagknows.service: cmd-exec
spec:
  clusterIP: None
  ports:
    - port: 7777
      name: serving
  selector:
    com.dagknows.service: cmd-exec
