---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: outpost
  labels:
    com.dagknows.service: outpost
spec:
  replicas: 1
  selector:
    matchLabels:
      com.dagknows.service: outpost
  template:
    metadata:
      labels:
        com.dagknows.service: outpost
    spec:
      containers:
        - name: outpost
          image: gcr.io/{{SUPER_USER_ORG}}-proxy-images/outpost:latest ## - To be replaced by GCR image.
          imagePullPolicy: "Always"
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 500Mi
          command: ["./main"]
          env:
            - name: PYENV_ROOT
              valueFrom:
                secretKeyRef:
                  name: com.dagknows.secret.frontend
                  key: PYENV_ROOT
            - name: PYRUNNER_ROOT
              valueFrom:
                secretKeyRef:
                  name: com.dagknows.secret.frontend
                  key: PYRUNNER_ROOT
            - name: PROXY_SESSION_ID
              valueFrom:
                secretKeyRef:
                  name: com.dagknows.secret.frontend
                  key: PROXY_SESSION_ID
            - name: PROXY_ALIAS
              valueFrom:
                secretKeyRef:
                  name: com.dagknows.secret.frontend
                  key: PROXY_ALIAS
            - name: SUPER_USER_ORG
              valueFrom:
                secretKeyRef:
                  name: com.dagknows.secret.frontend
                  key: SUPER_USER_ORG
            - name: DAGKNOWS_URL
              valueFrom:
                secretKeyRef:
                  name: com.dagknows.secret.frontend
                  key: DAGKNOWS_URL
            - name: DAGKNOWS_PROXY_URL
              valueFrom:
                secretKeyRef:
                  name: com.dagknows.secret.frontend
                  key: DAGKNOWS_PROXY_URL
            - name: DAGKNOWS_PROXY_ID
              valueFrom:
                secretKeyRef:
                  name: com.dagknows.secret.frontend
                  key: PROXY_SESSION_ID
          volumeMounts:
            - mountPath: /app/logs
              name: outpost-logs-vol
            - mountPath: /app/jobs
              name: outpost-jobs-vol
            - mountPath: /app/sidecar
              name: outpost-sidecar-vol
      volumes:
        - name: outpost-logs-vol
          persistentVolumeClaim:
            claimName: outpost-logs-pvc
        - name: outpost-jobs-vol
          persistentVolumeClaim:
            claimName: outpost-jobs-pvc
        - name: outpost-sidecar-vol
          persistentVolumeClaim:
            claimName: outpost-sidecar-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: outpost
  labels:
    com.dagknows.service: outpost
spec:
  clusterIP: None
  ports:
    - port: 9999
      name: serving
  selector:
    com.dagknows.service: outpost
