---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: outpost
  labels:
    com.dagknows.service: outpost
spec:
  replicas: 1
  selector:
    matchLabels:
      com.dagknows.service: outpost
  template:
    metadata:
      labels:
        com.dagknows.service: outpost
    spec:
      containers:
        - name: outpost
          image: gcr.io/{{SUPER_USER_ORG}}-dagknows-images/script_exec:latest ## - To be replaced by GCR image.
          imagePullPolicy: "Always"
          command: ["python", "src/script_exec.py"]
          env:
            - name: DAGKNOWS_URL
              valueFrom:
                secretKeyRef:
                  name: com.dagknows.secret.frontend
                  key: DAGKNOWS_URL
            - name: PYTHONPATH
              value: "/usr/src/app/src/userlibs"
            - name: PROXY_SESSION_ID
              valueFrom:
                secretKeyRef:
                  name: com.dagknows.secret.frontend
                  key: PROXY_SESSION_ID
          volumeMounts:
            - mountPath: /usr/src/app/logs
              name: logs-vol
      volumes:
        - name: logs-vol
          persistentVolumeClaim:
            claimName: outpost-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: outpost
  labels:
    com.dagknows.service: outpost
spec:
  clusterIP: None
  ports:
    - port: 5434
      name: serving
  selector:
    com.dagknows.service: outpost
