---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: outpost-logs-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      purpose: outpost-logs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: outpost-sidecar-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  selector:
    matchLabels:
      purpose: outpost-sidecar
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: outpost-jobs-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      purpose: outpost-jobs
